# Este es un servicio para establecer un valor booleano.
# Esto se puede usar para iniciar un proceso

bool enable  # Ejemplo: para habilitar o deshabilitar hardware
---
bool success   # Indica si el servicio se ejecutó con éxito
string message # Mensaje informativo, por ejemplo, para mensajes de error
